version: '3.7'

services:
  db:
    image: postgres
  web:
    build: .
    command: gunicorn --chdir /code/GenomicPrediction GenomicPrediction.wsgi --bind 0.0.0.0:8001 --workers 3
    volumes: 
     - .:/code
    
    ports:
     - "8001:8001"
    depends_on:
     - db
  redis:
    image: redis
    volumes:
     - ./redis.conf:/etc/redis.conf
    ports:
     - "6379"

    
      
